version: '3.8'

services:
  db:
    image: postgres
    container_name: pgdb
    restart: always
    environment:
      POSTGRES_DB: coursesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abc@123
    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: springboot-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/coursesdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: abc@123
    depends_on:
      - db
