version: '3'

services:
  postgres:
    image: postgres:13
    container_name: postgres-container
    environment:
      POSTGRES_DB: coursesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abc@123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    image: siddheshm303/backend-image:latest
    container_name: backend-container
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/coursesdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=abc@123
    depends_on:
      - postgres
    networks:
      - app-network

  frontend:
    image: siddheshm303/frontend-image-iitb:latest
    container_name: frontend-container
    ports:
      - "5173:80"
    environment:
      - REACT_APP_API_URL=http://backend:8080/api
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
